### ISSUE TITLE
Any plans for Explicit?

### ISSUE THREAD

**Issue by brucewlee** [najoungkim/pdtb3#10]
Hi. Do you have any plans to expand this repo/research to explicit discourse relation classification? This is a useful resource but it is shame that it is only limited to implicit. Especially considering there are several other areas of discourse parsing: explicit, connective classification, and etc. to build an End-to-End discourse parser.

**Comment by najoungkim** [comment]
Hi Bruce! I don't have plans to actively add new things for now. But I think explicit relations should be an easy change by tweaking the preprocessing code, for example for pdtb3, we're filtering for implicits here: https://github.com/najoungkim/pdtb3/blob/57a7abc2d004685f00c49952781075bfff7bd9ab/preprocess/preprocess_pdtb3.py#L86

Changing this to filter for explicits should give you a dataset for explicits (but of course sanity check), and I think this would just be compatible for running them through the models. 

Maybe try this and feel free to make a PR if you do? :)

**Comment by brucewlee** [comment]
Sounds good. I'll give it a try. I think it might be good as well to make adjustments for argument extraction, connective classification, etc. (in hopes that there is **one single** repo that all DP research use for evaluation). I find DP evaluation schemes especially messy among the other downstream tasks.
