### ISSUE TITLE
the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:450

### ISSUE THREAD

**Issue by Xu789** [najoungkim/pdtb3#8]
hello!
I follow the requirements(Python 3.7.3,PyTorch 1.1.0,CUDA 9.0.176) , but the following problems have been encountered：

**RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THC/THCBlas.cu:450**

Have you ever had such a problem..?

**Comment by najoungkim** [comment]
I don't think I've ran into the same problem, but it might be a more general pytorch issue. Maybe https://github.com/pytorch/pytorch/issues/7548 is relevant?

**Comment by Dominic124** [comment]
Hi, I have the same issue as yours, the same version of pytorch and cuda as well. Did you solve the problem?
